# Generated by Django 3.2.5 on 2021-08-23 08:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='question',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('qno', models.IntegerField()),
                ('question', models.CharField(max_length=100)),
                ('optiona', models.CharField(max_length=50)),
                ('optionb', models.CharField(max_length=50)),
                ('optionc', models.CharField(max_length=50)),
                ('optiond', models.CharField(max_length=50)),
                ('answer', models.CharField(max_length=50)),
            ],
        ),
    ]
