# Generated by Django 3.2.5 on 2021-08-23 11:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testapp', '0002_question'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='answer',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='question',
            name='optiona',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='question',
            name='optionb',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='question',
            name='optionc',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='question',
            name='optiond',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='question',
            name='qno',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='question',
            name='question',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='register',
            name='address',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='register',
            name='contact',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='register',
            name='email',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='register',
            name='fullname',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
